<?php /** @var Gemtoo\Blog\Block\Article\ListArticle $this */ ?>
<?php $_articles = $this->getArticles(); ?>
<div class="articles">
    <?php if ($_articles->getSize() > 0) :?>
        <div class="gemtoo-blog-articles-toolbar toolbar top"><?php echo $this->getPagerHtml(); ?></div>
        <div class="gemtoo-blog-articles-list-container">
            <?php foreach ($_articles as $_article) : ?>
                <div class="gemtoo-blog-article-list-item">
                    <a href="<?php echo $_article->getArticleUrl();?>"><?php echo $_article->getName();?></a>
                </div>
            <?php endforeach;?>
        </div>
        <div class="gemtoo-blog-articles-toolbar toolbar bottom"><?php echo $this->getPagerHtml(); ?></div>
    <?php else : ?>
        <?php echo __('There are no articles at this moment');?>
    <?php endif;?>
</div>
